// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package disw_designsystem.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class JA_CreateInitials_Template extends CustomJavaAction<java.lang.String>
{
	private java.lang.String Fullname;

	public JA_CreateInitials_Template(IContext context, java.lang.String Fullname)
	{
		super(context);
		this.Fullname = Fullname;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		if (this.Fullname == null) {
			return null;
		}
		if (this.Fullname.length() > 2) {
			String[] names = this.Fullname.split("\\s+");
			if (names.length == 1) {
				return names[0].substring(0, 2).toUpperCase();
			} else {
				String initials = names[0].substring(0, 1);
				initials = initials.concat(names[names.length - 1].substring(0, 1));
				return initials.toUpperCase();
			}
		}
		return this.Fullname.toUpperCase();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_CreateInitials_Template";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
